export { default as IconUser2Bold } from '../../assets/icons/Bold/2 User.svg';
export { default as IconUser3Bold } from '../../assets/icons/Bold/3 User.svg';
export { default as ActivityBold } from '../../assets/icons/Bold/Activity.svg';
export { default as AddUserBold } from '../../assets/icons/Bold/Add User.svg';
export { default as ArrowDown2Bold } from '../../assets/icons/Bold/Arrow - Down 2.svg';
export { default as ArrowDown3Bold } from '../../assets/icons/Bold/Arrow - Down 3.svg';

export { default as ArrowDownCircleBold } from '../../assets/icons/Bold/Arrow - Down Circle.svg';
export { default as ArrowDownSquareBold } from '../../assets/icons/Bold/Arrow - Down Square.svg';
export { default as ArrowDownBold } from '../../assets/icons/Bold/Arrow - Down.svg';
export { default as ArrowLeft2Bold } from '../../assets/icons/Bold/Arrow - Left 2.svg';
export { default as ArrowLeft3Bold } from '../../assets/icons/Bold/Arrow - Left 3.svg';
export { default as ArrowLeftCircleBold } from '../../assets/icons/Bold/Arrow - Left Circle.svg';
export { default as ArrowLeftSquareBold } from '../../assets/icons/Bold/Arrow - Left Square.svg';
export { default as ArrowLeftBold } from '../../assets/icons/Bold/Arrow - Left.svg';
export { default as ArrowRight2Bold } from '../../assets/icons/Bold/Arrow - Right 2.svg';
export { default as ArrowRight3Bold } from '../../assets/icons/Bold/Arrow - Right 3.svg';
export { default as ArrowRightCircleBold } from '../../assets/icons/Bold/Arrow - Right Circle.svg';
export { default as ArrowRightSquareBold } from '../../assets/icons/Bold/Arrow - Right Square.svg';
export { default as ArrowRightBold } from '../../assets/icons/Bold/Arrow - Right.svg';
export { default as ArrowUp2Bold } from '../../assets/icons/Bold/Arrow - Up 2.svg';
export { default as ArrowUp3Bold } from '../../assets/icons/Bold/Arrow - Up 3.svg';
export { default as ArrowUpCircleBold } from '../../assets/icons/Bold/Arrow - Up Circle.svg';
export { default as ArrowUpSquareBold } from '../../assets/icons/Bold/Arrow - Up Square.svg';
export { default as ArrowUpBold } from '../../assets/icons/Bold/Arrow - Up.svg';
export { default as Bag2Bold } from '../../assets/icons/Bold/Bag 2.svg';
export { default as BagBold } from '../../assets/icons/Bold/Bag.svg';
export { default as BookmarkBold } from '../../assets/icons/Bold/Bookmark.svg';
export { default as BuyBold } from '../../assets/icons/Bold/Buy.svg';
export { default as CalendarBold } from '../../assets/icons/Bold/Calendar.svg';
export { default as CallMissedBold } from '../../assets/icons/Bold/Call Missed.svg';
export { default as CallSilentBold } from '../../assets/icons/Bold/Call Silent.svg';
export { default as CallBold } from '../../assets/icons/Bold/Call.svg';
export { default as CallingBold } from '../../assets/icons/Bold/Calling.svg';
export { default as CameraBold } from '../../assets/icons/Bold/Camera.svg';
export { default as CategoryBold } from '../../assets/icons/Bold/Category.svg';
export { default as ChartBold } from '../../assets/icons/Bold/Chart.svg';
export { default as ChatBold } from '../../assets/icons/Bold/Chat.svg';
export { default as CloseSquareBold } from '../../assets/icons/Bold/Close Square.svg';
export { default as DangerBold } from '../../assets/icons/Bold/Danger.svg';
export { default as DeleteBold } from '../../assets/icons/Bold/Delete.svg';
export { default as DiscountBold } from '../../assets/icons/Bold/Discount.svg';
export { default as DiscoveryBold } from '../../assets/icons/Bold/Discovery.svg';
export { default as DocumentBold } from '../../assets/icons/Bold/Document.svg';
export { default as DownloadBold } from '../../assets/icons/Bold/Download.svg';
export { default as EditSquareBold } from '../../assets/icons/Bold/Edit Square.svg';
export { default as EditBold } from '../../assets/icons/Bold/Edit.svg';
export { default as Filter2Bold } from '../../assets/icons/Bold/Filter 2.svg';
export { default as FilterBold } from '../../assets/icons/Bold/Filter.svg';
export { default as FolderBold } from '../../assets/icons/Bold/Folder.svg';
export { default as GameBold } from '../../assets/icons/Bold/Game.svg';
export { default as GraphBold } from '../../assets/icons/Bold/Graph.svg';
export { default as HeartBold } from '../../assets/icons/Bold/Heart.svg';
export { default as HideBold } from '../../assets/icons/Bold/Hide.svg';
export { default as HomeBold } from '../../assets/icons/Bold/Home.svg';
export { default as Image2Bold } from '../../assets/icons/Bold/Image 2.svg';
export { default as ImageBold } from '../../assets/icons/Bold/Image.svg';
export { default as InfoCircleBold } from '../../assets/icons/Bold/Info Circle.svg';
export { default as InfoSquareBold } from '../../assets/icons/Bold/Info Square.svg';
export { default as LocationBold } from '../../assets/icons/Bold/Location.svg';
export { default as LockBold } from '../../assets/icons/Bold/Lock.svg';
export { default as LoginBold } from '../../assets/icons/Bold/Login.svg';
export { default as LogoutBold } from '../../assets/icons/Bold/Logout.svg';
export { default as MessageBold } from '../../assets/icons/Bold/Message.svg';
export { default as MoreCircleBold } from '../../assets/icons/Bold/More Circle.svg';
export { default as MoreSquareBold } from '../../assets/icons/Bold/More Square.svg';
export { default as NotificationBold } from '../../assets/icons/Bold/Notification.svg';
export { default as PaperDownloadBold } from '../../assets/icons/Bold/Paper Download.svg';
export { default as PaperFailBold } from '../../assets/icons/Bold/Paper Fail.svg';
export { default as PaperNegativeBold } from '../../assets/icons/Bold/Paper Negative.svg';
export { default as PaperPlusBold } from '../../assets/icons/Bold/Paper Plus.svg';
export { default as PaperUploadBold } from '../../assets/icons/Bold/Paper Upload.svg';
export { default as PaperBold } from '../../assets/icons/Bold/Paper.svg';
export { default as PasswordBold } from '../../assets/icons/Bold/Password.svg';
export { default as PlayBold } from '../../assets/icons/Bold/Play.svg';
export { default as PlusBold } from '../../assets/icons/Bold/Plus.svg';
export { default as ProfileBold } from '../../assets/icons/Bold/Profile.svg';
export { default as ScanBold } from '../../assets/icons/Bold/Scan.svg';
export { default as SearchBold } from '../../assets/icons/Bold/Search.svg';
export { default as SendBold } from '../../assets/icons/Bold/Send.svg';
export { default as SettingBold } from '../../assets/icons/Bold/Setting.svg';
export { default as ShieldDoneBold } from '../../assets/icons/Bold/Shield Done.svg';
export { default as ShieldFailBold } from '../../assets/icons/Bold/Shield Fail.svg';
export { default as ShowBold } from '../../assets/icons/Bold/Show.svg';
export { default as StarBold } from '../../assets/icons/Bold/Star.svg';
export { default as SwapBold } from '../../assets/icons/Bold/Swap.svg';
export { default as TickSquareBold } from '../../assets/icons/Bold/Tick Square.svg';
export { default as TicketStarBold } from '../../assets/icons/Bold/Ticket Star.svg';
export { default as TicketBold } from '../../assets/icons/Bold/Ticket.svg';
export { default as TimeCircleBold } from '../../assets/icons/Bold/Time Circle.svg';
export { default as TimeSquareBold } from '../../assets/icons/Bold/Time Square.svg';
export { default as UnlockBold } from '../../assets/icons/Bold/Unlock.svg';
export { default as UploadBold } from '../../assets/icons/Bold/Upload.svg';
export { default as VideoBold } from '../../assets/icons/Bold/Video.svg';
export { default as Voice2Bold } from '../../assets/icons/Bold/Voice 2.svg';
export { default as VoiceBold } from '../../assets/icons/Bold/Voice.svg';
export { default as VolumeDownBold } from '../../assets/icons/Bold/Volume Down.svg';
export { default as VolumeOffBold } from '../../assets/icons/Bold/Volume Off.svg';
export { default as VolumeUpBold } from '../../assets/icons/Bold/Volume Up.svg';
export { default as WalletBold } from '../../assets/icons/Bold/Wallet.svg';
export { default as WorkBold } from '../../assets/icons/Bold/Work.svg';

// Light

export { default as IconUser2Light } from '../../assets/icons/Light/2 User.svg';
export { default as IconUser3Light } from '../../assets/icons/Light/3 User.svg';
export { default as ActivityLight } from '../../assets/icons/Light/Activity.svg';
export { default as AddUserLight } from '../../assets/icons/Light/Add User.svg';
export { default as ArrowDown2Light } from '../../assets/icons/Light/Arrow - Down 2.svg';
export { default as ArrowDown3Light } from '../../assets/icons/Light/Arrow - Down 3.svg';
export { default as ArrowDownCircleLight } from '../../assets/icons/Light/Arrow - Down Circle.svg';
export { default as ArrowDownSquareLight } from '../../assets/icons/Light/Arrow - Down Square.svg';
export { default as ArrowDownLight } from '../../assets/icons/Light/Arrow - Down.svg';
export { default as ArrowLeft2Light } from '../../assets/icons/Light/Arrow - Left 2.svg';
export { default as ArrowLeft3Light } from '../../assets/icons/Light/Arrow - Left 3.svg';
export { default as ArrowLeftCircleLight } from '../../assets/icons/Light/Arrow - Left Circle.svg';
export { default as ArrowLeftSquareLight } from '../../assets/icons/Light/Arrow - Left Square.svg';
export { default as ArrowLeftLight } from '../../assets/icons/Light/Arrow - Left.svg';
export { default as ArrowRight2Light } from '../../assets/icons/Light/Arrow - Right 2.svg';
export { default as ArrowRight3Light } from '../../assets/icons/Light/Arrow - Right 3.svg';
export { default as ArrowRightCircleLight } from '../../assets/icons/Light/Arrow - Right Circle.svg';
export { default as ArrowRightSquareLight } from '../../assets/icons/Light/Arrow - Right Square.svg';
export { default as ArrowRightLight } from '../../assets/icons/Light/Arrow - Right.svg';
export { default as ArrowUp2Light } from '../../assets/icons/Light/Arrow - Up 2.svg';
export { default as ArrowUp3Light } from '../../assets/icons/Light/Arrow - Up 3.svg';
export { default as ArrowUpCircleLight } from '../../assets/icons/Light/Arrow - Up Circle.svg';
export { default as ArrowUpSquareLight } from '../../assets/icons/Light/Arrow - Up Square.svg';
export { default as ArrowUpLight } from '../../assets/icons/Light/Arrow - Up.svg';
export { default as Bag3Light } from '../../assets/icons/Light/Bag 3.svg';
export { default as BagLight } from '../../assets/icons/Light/Bag.svg';
export { default as BookmarkLight } from '../../assets/icons/Light/Bookmark.svg';
export { default as BuyLight } from '../../assets/icons/Light/Buy.svg';
export { default as CalendarLight } from '../../assets/icons/Light/Calendar.svg';
export { default as CallMissedLight } from '../../assets/icons/Light/Call Missed.svg';
export { default as CallSilentLight } from '../../assets/icons/Light/Call Silent.svg';
export { default as CallLight } from '../../assets/icons/Light/Call.svg';
export { default as CallingLight } from '../../assets/icons/Light/Calling.svg';
export { default as CameraLight } from '../../assets/icons/Light/Camera.svg';
export { default as CategoryLight } from '../../assets/icons/Light/Category.svg';
export { default as ChartLight } from '../../assets/icons/Light/Chart.svg';
export { default as ChatLight } from '../../assets/icons/Light/Chat.svg';
export { default as CloseSquareLight } from '../../assets/icons/Light/Close Square.svg';
export { default as DangerCircleLight } from '../../assets/icons/Light/Danger Circle.svg';
export { default as DangerTriangleLight } from '../../assets/icons/Light/Danger Triangle.svg';
export { default as DeleteLight } from '../../assets/icons/Light/Delete.svg';
export { default as DiscountLight } from '../../assets/icons/Light/Discount.svg';
export { default as DiscoveryLight } from '../../assets/icons/Light/Discovery.svg';
export { default as DocumentLight } from '../../assets/icons/Light/Document.svg';
export { default as DownloadLight } from '../../assets/icons/Light/Download.svg';
export { default as EditSquareLight } from '../../assets/icons/Light/Edit Square.svg';
export { default as EditLight } from '../../assets/icons/Light/Edit.svg';
export { default as Filter3Light } from '../../assets/icons/Light/Filter 3.svg';
export { default as FilterLight } from '../../assets/icons/Light/Filter.svg';
export { default as FolderLight } from '../../assets/icons/Light/Folder.svg';
export { default as GameLight } from '../../assets/icons/Light/Game.svg';
export { default as GraphLight } from '../../assets/icons/Light/Graph.svg';
export { default as HeartLight } from '../../assets/icons/Light/Heart.svg';
export { default as HideLight } from '../../assets/icons/Light/Hide.svg';
export { default as HomeLight } from '../../assets/icons/Light/Home.svg';
export { default as Image3Light } from '../../assets/icons/Light/Image 3.svg';
export { default as ImageLight } from '../../assets/icons/Light/Image.svg';
export { default as InfoSquareLight } from '../../assets/icons/Light/Info Square.svg';
export { default as LocationLight } from '../../assets/icons/Light/Location.svg';
export { default as LockLight } from '../../assets/icons/Light/Lock.svg';
export { default as LoginLight } from '../../assets/icons/Light/Login.svg';
export { default as LogoutLight } from '../../assets/icons/Light/Logout.svg';
export { default as MessageLight } from '../../assets/icons/Light/Message.svg';
export { default as MoreCircleLight } from '../../assets/icons/Light/More Circle.svg';
export { default as MoreSquareLight } from '../../assets/icons/Light/More Square.svg';
export { default as NotificationLight } from '../../assets/icons/Light/Notification.svg';
export { default as PaperDownloadLight } from '../../assets/icons/Light/Paper Download.svg';
export { default as PaperFailLight } from '../../assets/icons/Light/Paper Fail.svg';
export { default as PaperNegativeLight } from '../../assets/icons/Light/Paper Negative.svg';
export { default as PaperPlusLight } from '../../assets/icons/Light/Paper Plus.svg';
export { default as PaperUploadLight } from '../../assets/icons/Light/Paper Upload.svg';
export { default as PaperLight } from '../../assets/icons/Light/Paper.svg';
export { default as PasswordLight } from '../../assets/icons/Light/Password.svg';
export { default as PlayLight } from '../../assets/icons/Light/Play.svg';
export { default as PlusLight } from '../../assets/icons/Light/Plus.svg';
export { default as ProfileLight } from '../../assets/icons/Light/Profile.svg';
export { default as ScanLight } from '../../assets/icons/Light/Scan.svg';
export { default as SearchLight } from '../../assets/icons/Light/Search.svg';
export { default as SendLight } from '../../assets/icons/Light/Send.svg';
export { default as SettingLight } from '../../assets/icons/Light/Setting.svg';
export { default as ShieldDoneLight } from '../../assets/icons/Light/Shield Done.svg';
export { default as ShieldFailLight } from '../../assets/icons/Light/Shield Fail.svg';
export { default as ShowLight } from '../../assets/icons/Light/Show.svg';
export { default as StarLight } from '../../assets/icons/Light/Star.svg';
export { default as SwapLight } from '../../assets/icons/Light/Swap.svg';
export { default as TickSquareLight } from '../../assets/icons/Light/Tick Square.svg';
export { default as TicketStarLight } from '../../assets/icons/Light/Ticket Star.svg';
export { default as TicketLight } from '../../assets/icons/Light/Ticket.svg';
export { default as TimeCircleLight } from '../../assets/icons/Light/Time Circle.svg';
export { default as TimeSquareLight } from '../../assets/icons/Light/Time Square.svg';
export { default as UnlockLight } from '../../assets/icons/Light/Unlock.svg';
export { default as UploadLight } from '../../assets/icons/Light/Upload.svg';
export { default as VideoLight } from '../../assets/icons/Light/Video.svg';
export { default as Voice3Light } from '../../assets/icons/Light/Voice 3.svg';
export { default as VoiceLight } from '../../assets/icons/Light/Voice.svg';
export { default as VolumeDownLight } from '../../assets/icons/Light/Volume Down.svg';
export { default as VolumeOffLight } from '../../assets/icons/Light/Volume Off.svg';
export { default as VolumeUpLight } from '../../assets/icons/Light/Volume Up.svg';
export { default as WalletLight } from '../../assets/icons/Light/Wallet.svg';
export { default as WorkLight } from '../../assets/icons/Light/Work.svg';
